### ISSUE TITLE
Missing key files

### ISSUE THREAD

**Issue by sugeryi** [marti5ini/GENCDA#1]
In the file frequentItemset.py, the statement 'from fim import apriori' reported an error,

**Comment by marti5ini** [comment]
Hello,

Thank you for uncovering the issue. 
'fim' is a Python package that needs to be installed.  I had managed the dependencies to avoid any problems, but it's possible that the package has been updated and there might be some compatibility issues. To resolve the error you encountered, you can try reinstalling it by following the instructions provided on their official webpage: https://borgelt.net/pyfim.html.

If you require any additional information, please feel free to reach out to me.

Best, Martina

**Comment by sugeryi** [comment]
thank you very much!




1344163401
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "marti5ini/GENCDA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月26日(星期五) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [marti5ini/GENCDA] Missing key files (Issue #1)





 
Hello,
 
Thank you for uncovering the issue.
 'fim' is a Python package that needs to be installed.  I had managed the dependencies to avoid any problems, but it's possible that the package has been updated and there might be some compatibility issues. To resolve the error you encountered, you can try reinstalling it by following the instructions provided on their official webpage: https://borgelt.net/pyfim.html.
 
If you require any additional information, please feel free to reach out to me.
 
Best, Martina

**Comment by sugeryi** [comment]
thank you very much!


1344163401
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "marti5ini/GENCDA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月26日(星期五) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [marti5ini/GENCDA] Missing key files (Issue #1)





 
Closed #1 as completed.
